services:
  image: travispocr-swiftdeploy:latest
  port: 3000
  mode: stable
  version: "1.0.0"
  restart_policy: unless-stopped
  log_volume: swiftdeploy-logs

nginx:
  image: nginx:latest
  port: 8080
  proxy_timeout: 30

opa:
  image: openpolicyagent/opa:latest
  port: 8181
  policies_dir: ./policies

network:
  name: swiftdeploy-net
  driver_type: bridge

meta:
  username: hngstage4b
  contact: hngstage4b@swiftdeploy.local